// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnwetrelqkusmoazszym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFud2V0cmVscWt1c21vYXpzenltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNTY2ODcsImV4cCI6MjA2MTczMjY4N30.ygHXHSjEZtDTm3dhBXXn4ftuhSWAFQiD5M12lzeYZPY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);